package pseo

var Competitors = []string{
	"wablas", "woowa", "whatsender", "manychat", "wati",
	"chatapi", "mews", "respond-io", "twilio-whatsapp", "messagebird",
	"360dialog", "interakt", "qiscus", "kommo", "take",
	"zoko", "hellotars", "yellow-messenger", "gupshup", "karix",
	"textlocal", "kaleyra", "sinch", "vonage", "infobip",
	"planify", "zendesk", "freshchat", "tawkto", "crisp",
	"intercom", "drift", "hubspot", "zoho-salesiq", "livechat",
	"tidio", "jivochat", "chatra", "smartsupp", "userlike",
	"olark", "purechat", "liveperson", "helpscout", "front",
}

var Industries = []struct{ Name, Slug, Icon string }{
	{"Restoran", "restoran", "🍽️"},
	{"Klinik", "klinik", "🏥"},
	{"Toko Online", "toko-online", "🛒"},
	{"Properti", "properti", "🏠"},
	{"Travel", "travel", "✈️"},
	{"Pendidikan", "pendidikan", "📚"},
	{"Otomotif", "otomotif", "🚗"},
	{"Fashion", "fashion", "👗"},
	{"Kecantikan", "kecantikan", "💄"},
	{"Kesehatan", "kesehatan", "💊"},
	{"Asuransi", "asuransi", "🛡️"},
	{"Perbankan", "perbankan", "🏦"},
	{"Retail", "retail", "🏪"},
	{"Food & Beverage", "food-beverage", "🍕"},
	{"Hotel", "hotel", "🏨"},
	{"Event Organizer", "event-organizer", "🎉"},
	{"Fotografi", "fotografi", "📸"},
	{"Laundry", "laundry", "👕"},
	{"Bengkel", "bengkel", "🔧"},
	{"Salon", "salon", "💇"},
	{"Gym & Fitness", "gym", "🏋️"},
	{"Kursus", "kursus", "🎓"},
	{"Konsultan", "konsultan", "📋"},
	{"Agen Properti", "agen-properti", "🏘️"},
	{"Distributor", "distributor", "📦"},
	{"UMKM", "umkm", "🏬"},
	{"Logistik", "logistik", "🚚"},
	{"Farmasi", "farmasi", "💉"},
	{"Elektronik", "elektronik", "📱"},
	{"Petshop", "petshop", "🐾"},
	{"Konveksi", "konveksi", "🧵"},
	{"Percetakan", "percetakan", "🖨️"},
	{"Florist", "florist", "💐"},
	{"Toko Bangunan", "toko-bangunan", "🏗️"},
	{"Sembako", "sembako", "🛍️"},
	{"Oleh-Oleh", "oleh-oleh", "🎁"},
	{"Travel Agent", "travel-agent", "🧳"},
	{"Wedding Organizer", "wedding-organizer", "💒"},
	{" Digital Agency", "digital-agency", "💻"},
	{"Security", "security", "🔒"},
}

var Cities = []struct{ Name, Slug, Province string }{
	{"Jakarta Pusat", "jakarta-pusat", "DKI Jakarta"},
	{"Jakarta Barat", "jakarta-barat", "DKI Jakarta"},
	{"Jakarta Selatan", "jakarta-selatan", "DKI Jakarta"},
	{"Jakarta Timur", "jakarta-timur", "DKI Jakarta"},
	{"Jakarta Utara", "jakarta-utara", "DKI Jakarta"},
	{"Surabaya", "surabaya", "Jawa Timur"},
	{"Bandung", "bandung", "Jawa Barat"},
	{"Medan", "medan", "Sumatera Utara"},
	{"Semarang", "semarang", "Jawa Tengah"},
	{"Yogyakarta", "yogyakarta", "DIY"},
	{"Makassar", "makassar", "Sulawesi Selatan"},
	{"Palembang", "palembang", "Sumatera Selatan"},
	{"Tangerang", "tangerang", "Banten"},
	{"Bekasi", "bekasi", "Jawa Barat"},
	{"Depok", "depok", "Jawa Barat"},
	{"Bogor", "bogor", "Jawa Barat"},
	{"Malang", "malang", "Jawa Timur"},
	{"Solo", "solo", "Jawa Tengah"},
	{"Balikpapan", "balikpapan", "Kalimantan Timur"},
	{"Batam", "batam", "Kepulauan Riau"},
	{"Pekanbaru", "pekanbaru", "Riau"},
	{"Padang", "padang", "Sumatera Barat"},
	{"Denpasar", "denpasar", "Bali"},
	{"Manado", "manado", "Sulawesi Utara"},
	{"Banjarmasin", "banjarmasin", "Kalimantan Selatan"},
	{"Pontianak", "pontianak", "Kalimantan Barat"},
	{"Samarinda", "samarinda", "Kalimantan Timur"},
	{"Bandar Lampung", "bandar-lampung", "Lampung"},
	{"Jambi", "jambi", "Jambi"},
	{"Banda Aceh", "banda-aceh", "Aceh"},
	{"Mataram", "mataram", "NTB"},
	{"Ambon", "ambon", "Maluku"},
	{"Jayapura", "jayapura", "Papua"},
	{"Kupang", "kupang", "NTT"},
	{"Cirebon", "cirebon", "Jawa Barat"},
	{"Tasikmalaya", "tasikmalaya", "Jawa Barat"},
	{"Serang", "serang", "Banten"},
	{"Cilegon", "cilegon", "Banten"},
	{"Kediri", "kediri", "Jawa Timur"},
	{"Madiun", "madiun", "Jawa Timur"},
	{"Mojokerto", "mojokerto", "Jawa Timur"},
	{"Pasuruan", "pasuruan", "Jawa Timur"},
	{"Probolinggo", "probolinggo", "Jawa Timur"},
	{"Sukabumi", "sukabumi", "Jawa Barat"},
	{"Cimahi", "cimahi", "Jawa Barat"},
	{"Tegal", "tegal", "Jawa Tengah"},
	{"Pekalongan", "pekalongan", "Jawa Tengah"},
	{"Magelang", "magelang", "Jawa Tengah"},
	{"Salatiga", "salatiga", "Jawa Tengah"},
	{"Purwokerto", "purwokerto", "Jawa Tengah"},
	{"Kendari", "kendari", "Sulawesi Tenggara"},
	{"Palu", "palu", "Sulawesi Tengah"},
	{"Gorontalo", "gorontalo", "Gorontalo"},
	{"Ternate", "ternate", "Maluku Utara"},
	{"Banyuwangi", "banyuwangi", "Jawa Timur"},
	{"Jember", "jember", "Jawa Timur"},
	{"Gresik", "gresik", "Jawa Timur"},
	{"Sidoarjo", "sidoarjo", "Jawa Timur"},
	{"Batu", "batu", "Jawa Timur"},
	{"Blitar", "blitar", "Jawa Timur"},
	{"Tulungagung", "tulungagung", "Jawa Timur"},
	{"Bojonegoro", "bojonegoro", "Jawa Timur"},
	{"Lamongan", "lamongan", "Jawa Timur"},
	{"Klaten", "klaten", "Jawa Tengah"},
	{"Kudus", "kudus", "Jawa Tengah"},
	{"Pati", "pati", "Jawa Tengah"},
	{"Brebes", "brebes", "Jawa Tengah"},
	{"Banyumas", "banyumas", "Jawa Tengah"},
	{"Purbalingga", "purbalingga", "Jawa Tengah"},
	{"Kebumen", "kebumen", "Jawa Tengah"},
	{"Wonosobo", "wonosobo", "Jawa Tengah"},
	{"Temanggung", "temanggung", "Jawa Tengah"},
	{"Boyolali", "boyolali", "Jawa Tengah"},
	{"Sragen", "sragen", "Jawa Tengah"},
	{"Karanganyar", "karanganyar", "Jawa Tengah"},
	{"Wonogiri", "wonogiri", "Jawa Tengah"},
	{"Subang", "subang", "Jawa Barat"},
	{"Purwakarta", "purwakarta", "Jawa Barat"},
	{"Karawang", "karawang", "Jawa Barat"},
	{"Cianjur", "cianjur", "Jawa Barat"},
	{"Garut", "garut", "Jawa Barat"},
	{"Sumedang", "sumedang", "Jawa Barat"},
	{"Indramayu", "indramayu", "Jawa Barat"},
	{"Majalengka", "majalengka", "Jawa Barat"},
	{"Kuningan", "kuningan", "Jawa Barat"},
	{"Pangandaran", "pangandaran", "Jawa Barat"},
	{"Banjaran", "banjaran", "Jawa Barat"},
	{"Lhokseumawe", "lhokseumawe", "Aceh"},
	{"Langsa", "langsa", "Aceh"},
	{"Binjai", "binjai", "Sumatera Utara"},
	{"Tebing Tinggi", "tebing-tinggi", "Sumatera Utara"},
	{"Pematangsiantar", "pematangsiantar", "Sumatera Utara"},
	{"Tanjung Balai", "tanjung-balai", "Sumatera Utara"},
	{"Sibolga", "sibolga", "Sumatera Utara"},
	{"Padang Sidempuan", "padang-sidempuan", "Sumatera Utara"},
	{"Dumai", "dumai", "Riau"},
	{"Bengkulu", "bengkulu", "Bengkulu"},
	{"Pangkal Pinang", "pangkal-pinang", "Bangka Belitung"},
	{"Tanjung Pinang", "tanjung-pinang", "Kepulauan Riau"},
	{"Palangkaraya", "palangkaraya", "Kalimantan Tengah"},
	{"Tarakan", "tarakan", "Kalimantan Utara"},
	{"Bontang", "bontang", "Kalimantan Timur"},
	{"Singkawang", "singkawang", "Kalimantan Barat"},
	{"Bima", "bima", "NTB"},
	{"Sumbawa", "sumbawa", "NTB"},
	{"Maumere", "maumere", "NTT"},
	{"Ende", "ende", "NTT"},
	{"Ruteng", "ruteng", "NTT"},
	{"Sorong", "sorong", "Papua Barat"},
	{"Manokwari", "manokwari", "Papua Barat"},
	{"Merauke", "merauke", "Papua"},
	{"Timika", "timika", "Papua"},
	{"Biak", "biak", "Papua"},
	{"Parepare", "parepare", "Sulawesi Selatan"},
	{"Palopo", "palopo", "Sulawesi Selatan"},
	{"Bone", "bone", "Sulawesi Selatan"},
	{"Luwuk", "luwuk", "Sulawesi Tengah"},
	{"Bitung", "bitung", "Sulawesi Utara"},
	{"Tomohon", "tomohon", "Sulawesi Utara"},
	{"Kotamobagu", "kotamobagu", "Sulawesi Utara"},
	{"Bau-Bau", "bau-bau", "Sulawesi Tenggara"},
	{"Kolaka", "kolaka", "Sulawesi Tenggara"},
}

var Features = []struct{ Slug, Title, Desc string }{
	{"auto-reply", "Auto Reply WhatsApp", "Balas otomatis chat WhatsApp dengan keyword, AI, atau kombinasi keduanya. Support spintax {Halo|Hai} dan multi-bahasa."},
	{"broadcast", "Broadcast WhatsApp", "Kirim pesan massal ke ribuan kontak sekaligus. Round-robin multi-akun, interval configurable, anti-banned."},
	{"chatbot-ai", "Chatbot AI WhatsApp", "Chatbot pintar dengan AI OpenAI/DeepSeek/Gemini. Bisa search FAQ, training campaign, memory window."},
	{"multi-account", "Multi Account WhatsApp", "Kelola banyak nomor WA dalam satu dashboard. Assign berbeda per campaign/autoreply."},
	{"api-gateway", "API Gateway WhatsApp", "Kirim pesan via REST API. Support webhook, API Key auth. Integrasi ke sistem manapun."},
	{"integrasi", "Integrasi WhatsApp", "Integrasi dengan CRM, e-commerce, payment gateway. Webhook real-time + REST API."},
	{"laporan-analitik", "Laporan & Analitik", "Dashboard chart harian, sent/received stats, campaign analytics, agent performance."},
	{"manajemen-kontak", "Manajemen Kontak", "Import CSV, grup, tag, merge duplikat, unsubscribe, customer profile."},
	{"blast-messaging", "Blast Messaging", "Kirim pesan massal dengan template variabel {name} {phone}. Drip campaign multi-step."},
	{"scheduled-message", "Scheduled Message", "Jadwalkan pesan di jam/tanggal tertentu. Recurring daily/weekly auto-repeat."},
	{"template-pesan", "Template Pesan", "Simpan template dengan spintax & variabel. Quick-insert dari inbox chat."},
	{"drip-campaign", "Drip Campaign", "Rangkaian pesan otomatis bertahap. Auto-enroll, delay per step, stop keyword."},
	{"whatsapp-blast", "WhatsApp Blast", "Kirim pesan massal ke ribuan nomor dengan aman. Anti-banned system."},
	{"whatsapp-gateway", "WhatsApp Gateway", "Gateway WhatsApp multi-account untuk kirim & terima pesan via API."},
}

var BestPages = []struct{ Slug, Title, Keyword string }{
	{"whatsapp-marketing-tools", "Tools WhatsApp Marketing Terbaik", "WhatsApp Marketing"},
	{"whatsapp-broadcast-tools", "Tools Broadcast WhatsApp Terbaik", "Broadcast WhatsApp"},
	{"whatsapp-chatbot", "Chatbot WhatsApp Terbaik", "Chatbot WhatsApp"},
	{"whatsapp-auto-reply", "Auto Reply WhatsApp Terbaik", "Auto Reply WhatsApp"},
	{"whatsapp-gateway", "WhatsApp Gateway Terbaik", "WhatsApp Gateway"},
	{"whatsapp-api", "WhatsApp API Terbaik", "WhatsApp API"},
	{"whatsapp-business-tools", "Tools WhatsApp Business Terbaik", "WhatsApp Business"},
	{"whatsapp-blast", "Tools Blast WhatsApp Terbaik", "Blast WhatsApp"},
}

var SourceCodePages = []struct{ Slug, Title string }{
	{"beli-aplikasi-whatsapp-marketing", "Beli Aplikasi WhatsApp Marketing Self-Hosted"},
	{"beli-aplikasi-whatsapp-broadcast", "Beli Aplikasi WhatsApp Broadcast"},
	{"beli-aplikasi-whatsapp-chatbot", "Beli Aplikasi Chatbot WhatsApp AI"},
	{"beli-aplikasi-whatsapp-auto-reply", "Beli Aplikasi Auto Reply WhatsApp"},
	{"beli-aplikasi-whatsapp-gateway", "Beli Aplikasi WhatsApp Gateway API"},
	{"source-code-whatsapp-marketing", "Source Code WhatsApp Marketing Platform"},
	{"source-code-whatsapp-blast", "Source Code WhatsApp Blast / Sender"},
	{"source-code-chatbot-whatsapp", "Source Code Chatbot WhatsApp + AI"},
	{"source-code-whatsapp-gateway", "Source Code WhatsApp Gateway Multi-Account"},
	{"source-code-auto-reply-whatsapp", "Source Code Auto Reply WhatsApp"},
	{"aplikasi-whatsapp-marketing-self-hosted", "Aplikasi WhatsApp Marketing Self-Hosted"},
	{"aplikasi-whatsapp-blast-murah", "Aplikasi WhatsApp Blast Murah"},
	{"aplikasi-whatsapp-gateway-multi-account", "Aplikasi WhatsApp Gateway Multi Account"},
	{"aplikasi-chatbot-whatsapp-ai", "Aplikasi Chatbot WhatsApp AI"},
	{"aplikasi-auto-reply-whatsapp", "Aplikasi Auto Reply WhatsApp"},
	{"jual-source-code-whatsapp", "Jual Source Code Aplikasi WhatsApp"},
	{"jual-aplikasi-whatsapp-marketing", "Jual Aplikasi WhatsApp Marketing"},
	{"jual-aplikasi-whatsapp-blast", "Jual Aplikasi WhatsApp Blast / Sender"},
	{"harga-source-code-whatsapp", "Harga Source Code WhatsApp Platform"},
}

var CaraPages = []struct{ Slug, Title, Desc string }{
	{"membuat-auto-reply-whatsapp", "Cara Membuat Auto Reply WhatsApp", "Panduan lengkap setup auto reply WhatsApp dengan keyword, AI, dan multi-account."},
	{"broadcast-whatsapp-tanpa-banned", "Cara Broadcast WhatsApp Tanpa Banned", "Teknik broadcast WhatsApp massal aman: interval, round-robin, rate limiting."},
	{"integrasi-api-whatsapp", "Cara Integrasi API WhatsApp", "Step-by-step integrasi WhatsApp API ke website, CRM, atau aplikasi custom."},
	{"membuat-chatbot-whatsapp-ai", "Cara Membuat Chatbot WhatsApp dengan AI", "Buat chatbot WhatsApp pakai OpenAI/DeepSeek: setup API key, system prompt, KB."},
	{"multi-account-whatsapp", "Cara Setup Multi Account WhatsApp", "Kelola 5, 10, atau 50+ nomor WhatsApp dalam satu dashboard."},
	{"whatsapp-marketing-untuk-bisnis", "Cara WhatsApp Marketing untuk Bisnis", "Strategi WhatsApp marketing: broadcast, drip campaign, template, analitik."},
	{"whatsapp-blast-murah", "Cara WhatsApp Blast Murah & Efektif", "WhatsApp blast tanpa aplikasi mahal: self-hosted, bayar sekali."},
	{"kirim-pesan-whatsapp-massal", "Cara Kirim Pesan WhatsApp Massal", "Panduan kirim pesan WhatsApp ke ribuan nomor: grup kontak, CSV, delay."},
	{"meningkatkan-penjualan-whatsapp", "Cara Meningkatkan Penjualan via WhatsApp", "Teknik closing & follow-up via WhatsApp untuk conversion rate tinggi."},
	{"buat-template-whatsapp", "Cara Membuat Template Pesan WhatsApp", "Template WhatsApp profesional: spintax, variabel, quick-reply."},
}

var ChatbotPages = []struct{ Slug, Title, Desc string }{
	{"whatsapp-ai", "Chatbot WhatsApp AI", "Chatbot WhatsApp dengan kecerdasan buatan: auto-reply cerdas, FAQ search, memory."},
	{"whatsapp-murah", "Chatbot WhatsApp Murah", "Chatbot WhatsApp self-hosted, bayar sekali, tanpa biaya bulanan."},
	{"whatsapp-toko-online", "Chatbot WhatsApp untuk Toko Online", "Chatbot e-commerce: katalog produk, auto-order, payment, CS 24/7."},
	{"whatsapp-restoran", "Chatbot WhatsApp untuk Restoran", "Chatbot restoran: menu digital, reservasi, order delivery, broadcast promo."},
	{"whatsapp-klinik", "Chatbot WhatsApp untuk Klinik", "Chatbot klinik: booking appointment, reminder jadwal, info layanan."},
	{"whatsapp-pendidikan", "Chatbot WhatsApp untuk Pendidikan", "Chatbot pendidikan: info kursus, pendaftaran, reminder jadwal, FAQ."},
}

var PanduanPages = []struct{ Slug, Title, Desc string }{
	{"whatsapp-marketing-pemula", "Panduan WhatsApp Marketing untuk Pemula", "Dari nol sampai bisa: setup WA Gateway, tambah kontak, broadcast, auto reply."},
	{"whatsapp-business-api", "Panduan WhatsApp Business API", "Setup WhatsApp Cloud API (Meta) + integrasi. Verifikasi bisnis, template, webhook."},
	{"whatsapp-marketing-strategy", "Panduan Strategi WhatsApp Marketing 2026", "Strategi WA marketing: personalisasi, segmentasi, drip campaign, A/B testing."},
	{"self-hosted-whatsapp", "Panduan Self-Hosted WhatsApp Platform", "Install & kelola platform WhatsApp di server sendiri. Setup VPS, MySQL, domain."},
}
